# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
timezone: UTC
markdown: kramdown
plugins:
  - jekyll-sitemap

# jekyll-seo-tag configuration
title: "Sunbird"
description: ""



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - yarn-error.log
  - .jekyll-cache/
  - netlify.toml
  - .gitignore

permalink: pretty

include:
  - _redirects
  - _pages/
